# Generated by Django 5.2.12 on 2026-04-25 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sotuv nuqtasi',
                'verbose_name_plural': 'Sotuv nuqtalari',
            },
        ),
        migrations.CreateModel(
            name='ProductTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_transit', "Yo'lda"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='in_transit', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_transfers', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='points.salespoint')),
            ],
            options={
                'verbose_name': "Mahsulot jo'natish",
                'verbose_name_plural': "Mahsulot jo'natishlar",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PointReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='points.salespoint')),
            ],
            options={
                'verbose_name': 'Nuqtadan qaytim',
                'verbose_name_plural': 'Nuqtadan qaytimlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='points.producttransfer')),
            ],
            options={
                'verbose_name': "Jo'natish elementi",
                'verbose_name_plural': "Jo'natish elementlari",
            },
        ),
        migrations.CreateModel(
            name='PointStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='points.salespoint')),
            ],
            options={
                'verbose_name': 'Nuqta ombori',
                'verbose_name_plural': 'Nuqta omborlari',
                'unique_together': {('point', 'product')},
            },
        ),
    ]
