# Generated by Django 5.2.12 on 2026-04-25 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('terminal', 'Terminal'), ('click', 'Click'), ('payme', 'Payme')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_bakery_sale', models.BooleanField(default=True, help_text='Asosiy nonvoyxonadan sotuv')),
                ('point', models.ForeignKey(blank=True, help_text="Nuqtada sotuv bo'lsa", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='points.salespoint')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trade.sale')),
            ],
            options={
                'verbose_name': 'Sotuv elementi',
                'verbose_name_plural': 'Sotuv elementlari',
            },
        ),
        migrations.CreateModel(
            name='UnsoldProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('burnt', 'Kuygan'), ('deformed', 'Shakli buzilgan'), ('expired', "Muddati o'tgan"), ('returned', 'Qaytarilgan'), ('other', 'Boshqa')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.salespoint')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsold', to='production.product')),
            ],
            options={
                'verbose_name': 'Sotilmagan mahsulot',
                'verbose_name_plural': 'Sotilmagan mahsulotlar',
                'ordering': ['-date'],
            },
        ),
    ]
