# Generated by Django 5.2.12 on 2026-04-25 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotuv narxi')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Xom ashyo kategoriyasi',
                'verbose_name_plural': 'Xom ashyo kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='FinishedProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Mavjud miqdor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='production.product')),
            ],
            options={
                'verbose_name': 'Tayyor mahsulot ombori',
                'verbose_name_plural': 'Tayyor mahsulot ombori',
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ishlab chiqarilgan miqdor')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Xom ashyo hisobdan chiqarildi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('baker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='production.product')),
            ],
            options={
                'verbose_name': 'Kunlik ishlab chiqarish',
                'verbose_name_plural': 'Kunlik ishlab chiqarish',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('unit', models.CharField(choices=[('kg', 'Kilogramm'), ('litr', 'Litr'), ('dona', 'Dona'), ('paket', 'Paket')], default='kg', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Miqdori')),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Minimal miqdor (ogohlantirish)')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Birlik narxi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.rawmaterialcategory')),
            ],
            options={
                'verbose_name': 'Xom ashyo',
                'verbose_name_plural': 'Xom ashyolar',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Yetkazib beruvchi')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='production.rawmaterial')),
            ],
            options={
                'verbose_name': 'Xom ashyo kirim',
                'verbose_name_plural': 'Xom ashyo kirimlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='1 dona mahsulot uchun kerakli miqdor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='production.rawmaterial')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='production.product')),
            ],
            options={
                'verbose_name': 'Retsept (Texnologik xarita)',
                'verbose_name_plural': 'Retseptlar',
                'unique_together': {('product', 'material')},
            },
        ),
    ]
