# Generated by Django 5.2.12 on 2026-04-26 16:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lavozim nomi')),
                ('salary_type', models.CharField(choices=[('fixed', 'Fiksirlangan (oylik)'), ('piecework', 'Ishbay (sdelniy)'), ('mixed', 'Aralash')], default='fixed', max_length=20)),
                ('default_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Asosiy maosh (fiksirlangan)')),
            ],
            options={
                'verbose_name': 'Lavozim',
                'verbose_name_plural': 'Lavozimlar',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ishga kirgan sana')),
                ('dismiss_date', models.DateField(blank=True, null=True, verbose_name='Ishdan ketgan sana')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('vacation', "Ta'tilda"), ('sick', 'Kasal'), ('dismissed', 'Ishdan ketgan')], default='active', max_length=20)),
                ('fixed_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fiksirlangan oylik maosh')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('note', models.TextField(blank=True, verbose_name='Eslatma')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_profile', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.position')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_bonuses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Mukofot',
                'verbose_name_plural': 'Mukofotlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('cash_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advances', to='accounting.cashregister')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Avans',
                'verbose_name_plural': 'Avanslar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(verbose_name='Sabab')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_penalties', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Shtraf',
                'verbose_name_plural': 'Shtraflar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('day', 'Kunduzgi'), ('night', 'Tungi')], default='day', max_length=10)),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('late', 'Kech qoldi'), ('sick', 'Kasal'), ('vacation', "Ta'til")], default='present', max_length=10)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='PieceworkRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1 dona uchun summa')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piecework_rates', to='hr.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product')),
            ],
            options={
                'verbose_name': 'Ishbay tarifi',
                'verbose_name_plural': 'Ishbay tariflari',
                'unique_together': {('employee', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='YYYY-MM format', max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('piecework_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('units_produced', models.PositiveIntegerField(default=0)),
                ('bonus_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Loyiha (hisoblangan)'), ('paid', "To'langan")], default='draft', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments', to='accounting.cashregister')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='hr.employee')),
            ],
            options={
                'verbose_name': "Maosh to'lovi",
                'verbose_name_plural': "Maosh to'lovlari",
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
