# Generated by Django 5.2.12 on 2026-04-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='point',
            field=models.ForeignKey(blank=True, help_text='Sotuvchi qaysi nuqtaga biriktirilgan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='points.salespoint'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
