# Generated by Django 5.2.12 on 2026-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kassa nomi')),
                ('type', models.CharField(choices=[('main', 'Asosiy kassa (naqd)'), ('terminal', 'Terminal kassa'), ('electronic', "Elektron to'lov (Click/Payme)"), ('expense', 'Xarajat kassasi')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Joriy balans')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kassa',
                'verbose_name_plural': 'Kassalar',
            },
        ),
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Yetkazib beruvchi')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bizning qarzimiz')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kreditor',
                'verbose_name_plural': 'Kreditorlar',
            },
        ),
        migrations.CreateModel(
            name='CreditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_payment', models.BooleanField(default=False, help_text="True = biz to'ladik, False = yangi qarz")),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kredit yozuvi',
                'verbose_name_plural': 'Kredit yozuvlari',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ism/Kompaniya')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Umumiy qarz')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qarzdor',
                'verbose_name_plural': 'Qarzdorlar',
            },
        ),
        migrations.CreateModel(
            name='DebtRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_payment', models.BooleanField(default=False, help_text="True = to'lov, False = yangi qarz")),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Qarz yozuvi',
                'verbose_name_plural': 'Qarz yozuvlari',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('transfer', "O'tkazma")], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(verbose_name='Izoh')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('transfer', "O'tkazma")], max_length=20)),
            ],
            options={
                'verbose_name': 'Tranzaksiya kategoriyasi',
                'verbose_name_plural': 'Tranzaksiya kategoriyalari',
            },
        ),
    ]
